title: Eytan D.Netzer [EytanDn]
author: Eytan D.Netzer
email: EytanDn@gmail.com  
description: >- 
  My personal page on GitHub, my greeting card and resume, 
  and a place to share some of my projects and thoughts.
baseurl: "" 
url: "" 
github_username:  EytanDn

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
